"""The shared import contract. Raw records remain separate from derived metrics."""
def table(label, key, required, fields):
    result = {}
    for spec in fields.split(';'):
        name, title, kind = spec.split('|')
        result[name] = {'label': title, 'type': kind, 'required': name in required.split(',')}
    return {'label': label, 'key': key.split(','), 'fields': result}

SCHEMA = {
 'organizations': table('组织', 'organization_id', 'organization_id,organization_name', 'organization_id|组织编号|string;organization_name|组织名称|string;parent_organization_id|上级组织编号|string;organization_type|组织类型|string;business_line|业务线|string;cost_center_id|成本中心编号|string;manager_employee_id|负责人编号|string;effective_from|生效日期|date;effective_to|失效日期|date'),
 'job_grades': table('岗位职级', 'salary_band_id', 'salary_band_id,job_code,job_name,grade,currency,pay_basis,band_min,band_mid,band_max,effective_from', 'salary_band_id|薪酬标准编号|string;job_code|岗位编号|string;job_name|岗位名称|string;job_family|岗位序列|string;career_track|职业通道|string;grade|职级|string;location|适用地区|string;currency|币种|string;pay_basis|薪酬比较口径|string;band_min|薪酬下限|number;band_mid|中位标准|number;band_max|薪酬上限|number;effective_from|生效日期|date;effective_to|失效日期|date'),
 'employee_monthly': table('员工月度信息', 'employee_id,month', 'employee_id,month,organization_id,job_code,grade', 'employee_id|员工编号|string;month|月份|month;employee_name|员工姓名|string;organization_id|组织编号|string;job_code|岗位编号|string;grade|职级|string;salary_band_id|薪酬标准编号|string;location|工作地区|string;employment_type|用工类型|string;employment_status|在职状态|string;hire_date|入职日期|date;termination_date|离职日期|date;fte|全职当量|number;annual_salary_months|年计薪月数|number;standard_monthly_fixed_pay|标准月固定薪酬|number;target_annual_variable_pay|年度目标浮动薪酬|number'),
 'payroll_monthly': table('月度薪酬', 'employee_id,month', 'employee_id,month,currency,gross_cash_pay', 'employee_id|员工编号|string;month|月份|month;currency|币种|string;base_pay|基本工资|number;fixed_allowance|固定津贴|number;variable_allowance|浮动补贴|number;overtime_pay|加班费|number;performance_bonus|绩效奖金|number;commission_pay|提成|number;annual_bonus|年终奖|number;other_cash_pay|其他现金薪酬|number;pay_adjustment|补发扣减|number;gross_cash_pay|税前应发现金合计|number;employer_social_insurance|公司社保|number;employer_housing_fund|公司公积金|number;employer_benefit_cost|福利成本|number;other_employer_cost|其他用工成本|number;total_employer_cost|公司用工成本合计|number;paid_days|实际计薪天数|number;scheduled_days|应计薪天数|number'),
 'performance': table('绩效', 'employee_id,period_start,period_end,metric_name', 'employee_id,period_start,period_end,period_type', 'employee_id|员工编号|string;period_start|考核开始日期|date;period_end|考核结束日期|date;period_type|周期类型|string;performance_rating|绩效等级|string;performance_score|绩效分数|number;rating_scale_id|评分体系编号|string;target_value|目标值|number;actual_value|完成值|number;metric_name|指标名称|string;metric_unit|指标单位|string'),
 'commissions': table('提成明细', 'commission_id', 'commission_id,employee_id,business_period,payout_month', 'commission_id|提成记录编号|string;employee_id|员工编号|string;business_period|业务归属月份|month;payout_month|发放月份|month;project_or_order_id|项目订单编号|string;scheme_id|提成方案编号|string;rule_version|规则版本|string;calculation_basis|计算基准|string;eligible_amount|可计提金额|number;commission_rate|提成比例|number;calculated_commission|计算提成|number;adjustment_amount|调整额|number;payable_commission|应付提成|number;paid_commission|已付提成|number;payment_status|发放状态|string'),
 'business_metrics': table('业务指标', 'organization_id,month,metric_code', 'organization_id,month,metric_code,metric_value,metric_unit,aggregation_method', 'organization_id|组织编号|string;month|月份|month;metric_code|指标编号|string;metric_name|指标名称|string;metric_value|指标值|number;metric_unit|指标单位|string;currency|币种|string;metric_definition|指标口径|string;aggregation_method|汇总方式|string'),
 'market_benchmarks': table('市场薪酬', 'benchmark_id', 'benchmark_id,source,source_date,location,internal_job_code,internal_grade,pay_basis,currency,p50', 'benchmark_id|市场基准编号|string;source|数据来源|string;source_date|数据日期|date;industry|行业|string;company_size|公司规模|string;location|地区|string;market_job_name|市场岗位|string;market_grade|市场职级|string;internal_job_code|内部岗位编号|string;internal_grade|内部职级|string;pay_basis|薪酬口径|string;currency|币种|string;p25|市场P25|number;p50|市场P50|number;p75|市场P75|number;p90|市场P90|number;sample_size|样本量|number'),
 'salary_changes': table('调薪记录', 'change_id', 'change_id,employee_id,effective_date,before_fixed_pay,after_fixed_pay,pay_basis,currency', 'change_id|调薪记录编号|string;employee_id|员工编号|string;effective_date|生效日期|date;change_type|调薪类型|string;before_fixed_pay|调整前固定薪酬|number;after_fixed_pay|调整后固定薪酬|number;pay_basis|薪酬口径|string;currency|币种|string;before_grade|调整前职级|string;after_grade|调整后职级|string;reason|调薪原因|string'),
 'workforce_budget': table('编制预算', 'scenario_id,month,organization_id,job_code,grade', 'scenario_id,month,organization_id,job_code,grade,planned_fte', 'scenario_id|预算情景编号|string;month|月份|month;organization_id|组织编号|string;job_code|岗位编号|string;grade|职级|string;planned_fte|计划全职当量|number;planned_hires|计划入职人数|number;planned_exits|计划离职人数|number;planned_avg_monthly_fixed_pay|计划人均月固定薪酬|number;planned_variable_pay|计划浮动薪酬总额|number;planned_employer_contributions|计划公司缴费总额|number;planned_other_cost|计划其他成本总额|number;approved_budget|批准预算|number'),
}
CORE = ['organizations', 'job_grades', 'employee_monthly', 'payroll_monthly']
CASH = ['base_pay','fixed_allowance','variable_allowance','overtime_pay','performance_bonus','commission_pay','annual_bonus','other_cash_pay','pay_adjustment']
COST = ['employer_social_insurance','employer_housing_fund','employer_benefit_cost','other_employer_cost']
